//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMMO_Stocker.SmmoWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmmoWebService.ISmmoService")]
    public interface ISmmoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISmmoService/UpdateStock", ReplyAction="http://tempuri.org/ISmmoService/UpdateStockResponse")]
        void UpdateStock(string server, string user, double charStock, int guildStock);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmmoServiceChannel : SMMO_Stocker.SmmoWebService.ISmmoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmmoServiceClient : System.ServiceModel.ClientBase<SMMO_Stocker.SmmoWebService.ISmmoService>, SMMO_Stocker.SmmoWebService.ISmmoService {
        
        public SmmoServiceClient() {
        }
        
        public SmmoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmmoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmmoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmmoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateStock(string server, string user, double charStock, int guildStock) {
            base.Channel.UpdateStock(server, user, charStock, guildStock);
        }
    }
}
